import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';

import { AuthProvider } from '../contexts';

import { StyledRoot } from './StyledRoot';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <AppRouterCacheProvider>
            <StyledRoot>
              {children}
              <ToastContainer position="top-center" autoClose={2000} />
            </StyledRoot>
          </AppRouterCacheProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
