version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - 'ptchom'
    commit-message:
      prefix: 'chore'
    groups:
      production-dependencies:
        dependency-type: 'production'
      development-dependencies:
        dependency-type: 'development'
    ignore:
      - dependency-name: 'eslint'
        update-types: ['version-update:semver-major']
      - dependency-name: '@typescript-eslint/eslint-plugin'
      - dependency-name: '@typescript-eslint/parser'
      - dependency-name: 'typescript'
